# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /data/ssd_4tb/UnrealEngine/Linux_Unreal_Engine_5.7.3

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	SoulsGame-Android-DebugGame  \
	SoulsGame-Android-Development  \
	SoulsGame-Android-Shipping  \
	SoulsGame-Linux-DebugGame  \
	SoulsGame-Linux-Development  \
	SoulsGame-Linux-Shipping  \
	SoulsGame-LinuxArm64-DebugGame  \
	SoulsGame-LinuxArm64-Development  \
	SoulsGame-LinuxArm64-Shipping  \
	SoulsGame \
	SoulsGameEditor-Linux-DebugGame  \
	SoulsGameEditor-Linux-Development  \
	SoulsGameEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SoulsGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SoulsGameEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

SoulsGame-Android-DebugGame:
	 $(BUILD) SoulsGame Android DebugGame  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-Android-Development:
	 $(BUILD) SoulsGame Android Development  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-Android-Shipping:
	 $(BUILD) SoulsGame Android Shipping  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-Linux-DebugGame:
	 $(BUILD) SoulsGame Linux DebugGame  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-Linux-Development:
	 $(BUILD) SoulsGame Linux Development  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-Linux-Shipping:
	 $(BUILD) SoulsGame Linux Shipping  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-LinuxArm64-DebugGame:
	 $(BUILD) SoulsGame LinuxArm64 DebugGame  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-LinuxArm64-Development:
	 $(BUILD) SoulsGame LinuxArm64 Development  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame-LinuxArm64-Shipping:
	 $(BUILD) SoulsGame LinuxArm64 Shipping  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGame: SoulsGame-Linux-Development

SoulsGameEditor-Linux-DebugGame:
	 $(BUILD) SoulsGameEditor Linux DebugGame  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGameEditor-Linux-Development:
	 $(BUILD) SoulsGameEditor Linux Development  -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" $(ARGS)

SoulsGameEditor: SoulsGameEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/data/ssd_4tb/UnrealProjects/Soulslike/SoulsGame.uproject" -Game 

.PHONY: $(TARGETS)
